[tool.black]
line-length = 100

[tool.ruff]
line-length = 100
extend-select = ["E", "F", "W", "I"]
ignore = ["E501", "F401"]
exclude = [".venv", "tests/"]

[tool.mypy]
python_version = "3.11"
ignore_missing_imports = true
strict = true
exclude = 'tests/'

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q"
testpaths = [
    "tests",
]
