# Reference Genomes Configuration for GenoScope
# Defines available reference genomes and their locations

genomes:
  hg38:
    name: "Human Genome GRCh38/hg38"
    species: "Homo sapiens"
    version: "GRCh38.p14"
    release_date: "2023-02"
    files:
      fasta: 
        url: "https://hgdownload.soe.ucsc.edu/goldenPath/hg38/bigZips/hg38.fa.gz"
        md5: "f4f4d5e9c3b3a3d8c3b3a3d8c3b3a3d8"
        size: "938M"
      indexes:
        bwa: "hg38.fa.bwt"
        samtools: "hg38.fa.fai"
        gatk_dict: "hg38.dict"
        minimap2: "hg38.mmi"
    annotations:
      gtf: "https://ftp.ensembl.org/pub/release-110/gtf/homo_sapiens/Homo_sapiens.GRCh38.110.gtf.gz"
      gff3: "https://ftp.ensembl.org/pub/release-110/gff3/homo_sapiens/Homo_sapiens.GRCh38.110.gff3.gz"
    known_sites:
      dbsnp: "https://ftp.ncbi.nih.gov/snp/organisms/human_9606/VCF/00-All.vcf.gz"
      mills_indels: "https://storage.googleapis.com/genomics-public-data/resources/broad/hg38/v0/Mills_and_1000G_gold_standard.indels.hg38.vcf.gz"
      known_indels: "https://storage.googleapis.com/genomics-public-data/resources/broad/hg38/v0/Homo_sapiens_assembly38.known_indels.vcf.gz"
      hapmap: "https://storage.googleapis.com/genomics-public-data/resources/broad/hg38/v0/hapmap_3.3.hg38.vcf.gz"
      omni: "https://storage.googleapis.com/genomics-public-data/resources/broad/hg38/v0/1000G_omni2.5.hg38.vcf.gz"
      1000g_snps: "https://storage.googleapis.com/genomics-public-data/resources/broad/hg38/v0/1000G_phase1.snps.high_confidence.hg38.vcf.gz"
    features:
      chromosome_sizes: "hg38.chrom.sizes"
      centromeres: "hg38.centromeres.bed"
      gaps: "hg38.gaps.bed"
      repeat_masker: "hg38.repeatMasker.bed"

  hg19:
    name: "Human Genome GRCh37/hg19"
    species: "Homo sapiens"
    version: "GRCh37.p13"
    release_date: "2013-12"
    files:
      fasta:
        url: "https://hgdownload.soe.ucsc.edu/goldenPath/hg19/bigZips/hg19.fa.gz"
        md5: "a244d8a32473650b25c6e8e1654387d6"
        size: "905M"
      indexes:
        bwa: "hg19.fa.bwt"
        samtools: "hg19.fa.fai"
        gatk_dict: "hg19.dict"
        minimap2: "hg19.mmi"
    annotations:
      gtf: "https://ftp.ensembl.org/pub/grch37/current/gtf/homo_sapiens/Homo_sapiens.GRCh37.87.gtf.gz"
      gff3: "https://ftp.ensembl.org/pub/grch37/current/gff3/homo_sapiens/Homo_sapiens.GRCh37.87.gff3.gz"
    known_sites:
      dbsnp: "https://ftp.ncbi.nih.gov/snp/organisms/human_9606_b151_GRCh37p13/VCF/00-All.vcf.gz"
      mills_indels: "https://storage.googleapis.com/genomics-public-data/resources/broad/hg19/v0/Mills_and_1000G_gold_standard.indels.hg19.sites.vcf"
      known_indels: "https://storage.googleapis.com/genomics-public-data/resources/broad/hg19/v0/1000G_phase1.indels.hg19.sites.vcf"

  t2t_chm13:
    name: "T2T-CHM13 Complete Human Genome"
    species: "Homo sapiens"
    version: "v2.0"
    release_date: "2022-04"
    description: "Telomere-to-telomere complete human genome assembly"
    files:
      fasta:
        url: "https://s3-us-west-2.amazonaws.com/human-pangenomics/T2T/CHM13/assemblies/analysis_set/chm13v2.0.fa.gz"
        md5: "5c0949a1e2a8cf88b79e0e5c5e2e5f3d"
        size: "3.1G"
    special_features:
      - "Complete telomeres"
      - "Complete centromeres"
      - "No gaps"
      - "All chromosomes complete"

  mm10:
    name: "Mouse Genome mm10"
    species: "Mus musculus"
    version: "GRCm38.p6"
    release_date: "2020-06"
    files:
      fasta:
        url: "https://hgdownload.soe.ucsc.edu/goldenPath/mm10/bigZips/mm10.fa.gz"
        md5: "14fc789bb64b3e38e7c3d3dd458a6c3e"
        size: "830M"
      indexes:
        bwa: "mm10.fa.bwt"
        samtools: "mm10.fa.fai"
        gatk_dict: "mm10.dict"
    annotations:
      gtf: "https://ftp.ensembl.org/pub/release-102/gtf/mus_musculus/Mus_musculus.GRCm38.102.gtf.gz"
    known_sites:
      mgp_snps: "https://ftp.ebi.ac.uk/pub/databases/mousegenomes/REL-1505-SNPs_Indels/mgp.v5.merged.snps_all.dbSNP142.vcf.gz"
      mgp_indels: "https://ftp.ebi.ac.uk/pub/databases/mousegenomes/REL-1505-SNPs_Indels/mgp.v5.merged.indels.dbSNP142.normed.vcf.gz"

  mm39:
    name: "Mouse Genome mm39"
    species: "Mus musculus"
    version: "GRCm39"
    release_date: "2023-01"
    files:
      fasta:
        url: "https://hgdownload.soe.ucsc.edu/goldenPath/mm39/bigZips/mm39.fa.gz"
        md5: "7e5c7b7c7d7e5c7b7c7d7e5c7b7c7d7e"
        size: "850M"

  rn7:
    name: "Rat Genome rn7"
    species: "Rattus norvegicus"
    version: "mRatBN7.2"
    release_date: "2020-11"
    files:
      fasta:
        url: "https://hgdownload.soe.ucsc.edu/goldenPath/rn7/bigZips/rn7.fa.gz"
        md5: "8e8c8d8e8c8d8e8c8d8e8c8d8e8c8d8e"
        size: "870M"

  danrer11:
    name: "Zebrafish Genome danRer11"
    species: "Danio rerio"
    version: "GRCz11"
    release_date: "2017-05"
    files:
      fasta:
        url: "https://hgdownload.soe.ucsc.edu/goldenPath/danRer11/bigZips/danRer11.fa.gz"
        size: "370M"

  dm6:
    name: "Fruit Fly Genome dm6"
    species: "Drosophila melanogaster"
    version: "Release 6"
    release_date: "2014-08"
    files:
      fasta:
        url: "https://hgdownload.soe.ucsc.edu/goldenPath/dm6/bigZips/dm6.fa.gz"
        size: "43M"

  ce11:
    name: "C. elegans Genome ce11"
    species: "Caenorhabditis elegans"
    version: "WBcel235"
    release_date: "2013-02"
    files:
      fasta:
        url: "https://hgdownload.soe.ucsc.edu/goldenPath/ce11/bigZips/ce11.fa.gz"
        size: "30M"

  saccer3:
    name: "Yeast Genome sacCer3"
    species: "Saccharomyces cerevisiae"
    version: "S288C"
    release_date: "2011-04"
    files:
      fasta:
        url: "https://hgdownload.soe.ucsc.edu/goldenPath/sacCer3/bigZips/sacCer3.fa.gz"
        size: "3.7M"

# Viral genomes for pathogen detection
viral_genomes:
  sars_cov_2:
    name: "SARS-CoV-2"
    species: "Severe acute respiratory syndrome coronavirus 2"
    version: "NC_045512.2"
    files:
      fasta:
        url: "https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/009/858/895/GCF_009858895.2_ASM985889v3/GCF_009858895.2_ASM985889v3_genomic.fna.gz"
        size: "30K"

# Configuration for genome downloads
download_settings:
  max_retries: 3
  chunk_size: 8192
  verify_md5: true
  decompress: true
  index_after_download: true
  parallel_downloads: 2
  
# Default paths
paths:
  base_dir: "${HOME}/.genoscope/references"
  download_dir: "${base_dir}/downloads"
  index_dir: "${base_dir}/indexes"
  annotation_dir: "${base_dir}/annotations"
