# .pre-commit-config.yaml
repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.4.3
  hooks: [ { id: ruff } ]
- repo: https://github.com/psf/black
  rev: 24.4.2
  hooks: [ { id: black } ]
- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: v0.4.3
  hooks: [ { id: ruff-format } ]
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.10.0
  hooks: [ { id: mypy } ]
- repo: https://github.com/PyCQA/bandit
  rev: v1.7.8
  hooks: [ { id: bandit } ]
